server:
  port: 7073
spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://127.0.0.1:3306/spring_erp?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: admin
    password: admin@123
  elasticsearch:
    uris: http://192.168.140.215:9200
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
    timeout: 5000

management:
  health:
    rabbit:
      enabled: false
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
